/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NMMDatabase.java
 *
 * Created on 2010-07-29, 18:56:17
 */

package nmm2010;

import biz.ekoplan.nmm2010.devices.NMMNoiseMeasurementSet;
import biz.ekoplan.nmm2010.enums.RecordValueType;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import biz.ekoplan.nmm2010.measurement.NMMMeasurement;
import java.util.Locale;
import biz.ekoplan.nmm2010.enums.RecordValueType;
import biz.ekoplan.nmm2010.enums.TimePeriods;
import biz.ekoplan.nmm2010.toolbox.NMMNumberInputVerifier;
import javax.swing.JComboBox;

/**
 *
 * @author samsung
 */
public class NMMDatabase extends javax.swing.JDialog {

    Connection con;
    NMMProject nmmproj;
    float dane[];
    int rozmiarTablicy;
    Locale locale;
    NMMNumberInputVerifier niv;

    final boolean DEBUG = false;

    /** Creates new form NMMDatabase */
    public NMMDatabase(java.awt.Frame parent, boolean modal, 
            float tablicaDanych[], int rTablicy, NMMProject nmmproject, Locale _locale) {
        super(parent, modal);
        nmmproj=nmmproject;
        initComponents();
        this.setLocationRelativeTo(null);
        dane=tablicaDanych;
        this.rozmiarTablicy=rTablicy;
        this.locale=_locale;
        this.comboMeasurements.removeAllItems();
        if (this.nmmproj.getMeasurementsNumber()>0) {
            for (int i=0; i<this.nmmproj.getMeasurementsNumber();i++) {
                this.comboMeasurements.addItem(this.nmmproj.getMeasurement(i));
            }
        }        
        this.comboMeasurements.addItem("New measurement");
        this.niv = new NMMNumberInputVerifier();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboDeviceName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtfieldMeasurementDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfieldLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfieldProjectNumber = new javax.swing.JTextField();
        jbuttonCancel = new javax.swing.JButton();
        jbuttonSend = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtextfieldTime = new javax.swing.JTextField();
        comboboxSendTo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboMetrics = new JComboBox(RecordValueType.values());
        jLabel10 = new javax.swing.JLabel();
        comboMeasurements = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        texLoggedEvery = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data properties and destination");

        jLabel1.setText("Send to:");

        jLabel2.setText("Device");

        comboDeviceName.setModel(this.nmmproj.getMeasuringSets());

        jLabel3.setText("Date");

        txtfieldMeasurementDate.setText("2011-01-01");

        jLabel4.setText("Location");

        txtfieldLocation.setText("PnPPH");

        jLabel5.setText("Project");

        txtfieldProjectNumber.setText("LAE_nn_rrrr");

        jbuttonCancel.setText("Cancel");
        jbuttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCancelActionPerformed(evt);
            }
        });

        jbuttonSend.setText("Send");
        jbuttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSendActionPerformed(evt);
            }
        });

        jLabel6.setText("Time");

        jtextfieldTime.setText("05:59:00");

        comboboxSendTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MS Access", "NMM Project" }));
        comboboxSendTo.setSelectedIndex(1);
        comboboxSendTo.setToolTipText("Select destination for imported data.");

        jLabel7.setText("yyyy-mm-dd");

        jLabel8.setText("hh:mm:ss");

        jLabel9.setText("Metric");

        jLabel10.setText("Measurement:");

        comboMeasurements.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Logged every :");

        texLoggedEvery.setText("1000");
        texLoggedEvery.setInputVerifier(this.niv);

        jLabel12.setText("ms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxSendTo, 0, 321, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbuttonSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboMetrics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboMeasurements, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(comboDeviceName, 0, 322, Short.MAX_VALUE)
                            .addComponent(txtfieldLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(txtfieldProjectNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtfieldMeasurementDate, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtextfieldTime, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texLoggedEvery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboboxSendTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfieldMeasurementDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfieldProjectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(comboMetrics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(comboMeasurements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(texLoggedEvery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbuttonCancel)
                            .addComponent(jbuttonSend)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtextfieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSendActionPerformed


        Date d1=new Date();
        DateFormat df = DateFormat.getTimeInstance();
        GregorianCalendar cal = new GregorianCalendar();

        String godz = this.jtextfieldTime.getText().substring(0, 2);
        String min = this.jtextfieldTime.getText().substring(3, 5);
        String sek = this.jtextfieldTime.getText().substring(6, 8);
        
        String year = this.txtfieldMeasurementDate.getText().substring(0, 4);
        String month = this.txtfieldMeasurementDate.getText().substring(5, 7);
        String day = this.txtfieldMeasurementDate.getText().substring(8, 10);

        cal.set(Integer.parseInt(year),Integer.parseInt(month),Integer.parseInt(day),
                Integer.parseInt(godz),Integer.parseInt(min),(int)Integer.parseInt(sek));

        d1.setTime(cal.getTimeInMillis());
        String time=df.format(d1);
        String kwerenda;

        // Jeżeli wybrano wysłanie danych do bazy MS Access to tutaj...
        if (this.comboboxSendTo.getModel().getSelectedItem().toString().equals("MS Access")) {
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:vkarta2010", "", "");
            Statement stmt = con.createStatement();
            String nazwaTabeli = "";
            nazwaTabeli=this.comboDeviceName.getModel().getSelectedItem().toString()+
                    "_"+this.txtfieldMeasurementDate.getText()+
                    "_"+this.txtfieldLocation.getText()+
                    "_"+this.txtfieldProjectNumber.getText();
            if (this.DEBUG) {
                System.out.println("Wstawiam do bazy nową tabelę: "+nazwaTabeli);
            }            
            stmt.execute("CREATE TABLE "+nazwaTabeli+" (TIME_ varchar(8), "
                    + "PARAM1 real, PAUSE bit, AUTONUMER int)");
            if (this.DEBUG) {
                System.out.print("Wstawię do tabeli "+this.rozmiarTablicy+" "
                    + "rekordów. Cierpliwości ...");
            }            
            for (int j=0; j<this.rozmiarTablicy;j++) {
                d1.setTime(cal.getTimeInMillis()+j*1000);
                time=df.format(d1);
                kwerenda="INSERT INTO "+nazwaTabeli+" VALUES ('"+time+"', "+
                        dane[j]+", 1, "+j+")";
                stmt.addBatch(kwerenda);
                System.out.print(".");
            }

            if (this.DEBUG) {
                System.out.println("\nPrzesyłam kwerendę wstawienia danych!");
            }            
            stmt.executeBatch();
            if (this.DEBUG) {
                System.out.println("Wstawiłem!");
            }            
            stmt.close();

        } catch (ClassNotFoundException exc) {
            System.out.println("Brak klasy sterownika...");
            System.out.println(exc);
        } catch (SQLException exc ) {
            System.out.println("Problem z ustanowieniem połączenia...");
            System.out.println(exc);
        }
        }

        
        NMMMeasurement ms;
        // Jeżeli wybrano przesłanie danych do obiektu projektu programu NMM to tutaj...
        if (this.comboboxSendTo.getModel().getSelectedItem().toString().equals("NMM Project")) {
            
            
            
            if (this.comboMeasurements.getSelectedItem() instanceof NMMMeasurement) {
                ms = (NMMMeasurement)this.comboMeasurements.getSelectedItem();
                for (int j=0; j<this.rozmiarTablicy;j++) {                
                    ms.addToRecord((RecordValueType)this.comboMetrics.getSelectedItem(), dane[j], j);
                }
            } else {
                ms = new NMMMeasurement(this.txtfieldMeasurementDate.getText(),
                    this.jtextfieldTime.getText(),
                    Long.parseLong(this.texLoggedEvery.getText()), this.locale);                    
                for (int j=0; j<this.rozmiarTablicy;j++) {                
                    ms.addRecord((RecordValueType)this.comboMetrics.getSelectedItem(), dane[j]);
                }
            }                            
        ms.updateLeq();        
        ms.setDescription(this.txtfieldLocation.getText());
        if (this.comboDeviceName.getSelectedIndex()!=-1) {
            ms.setMeasurementSet((NMMNoiseMeasurementSet)this.comboDeviceName.getSelectedItem());
        } else {
            ms.setMeasurementSet(null);
        }
        this.nmmproj.addMeasurement(ms);
        }
        this.nmmproj.setSaved(false);
        this.dispose();
    }//GEN-LAST:event_jbuttonSendActionPerformed

    private void jbuttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbuttonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboDeviceName;
    private javax.swing.JComboBox comboMeasurements;
    private javax.swing.JComboBox comboMetrics;
    private javax.swing.JComboBox comboboxSendTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbuttonCancel;
    private javax.swing.JButton jbuttonSend;
    private javax.swing.JTextField jtextfieldTime;
    private javax.swing.JTextField texLoggedEvery;
    private javax.swing.JTextField txtfieldLocation;
    private javax.swing.JTextField txtfieldMeasurementDate;
    private javax.swing.JTextField txtfieldProjectNumber;
    // End of variables declaration//GEN-END:variables

}
