/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NMMEventsTable.java
 *
 * Created on 2010-12-12, 00:23:53
 */

package nmm2010;

import biz.ekoplan.nmm2010.toolbox.NMMToolbox;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class NMMEventsTable extends javax.swing.JDialog {

    NMMProject nmmproj;
    NMMEventsTableModel tm;

    /** Creates new form NMMEventsTable */
    public NMMEventsTable(java.awt.Frame parent, boolean modal, NMMProject nmmproj, NMMEventsTableModel etm) {
        super(parent, modal);
        tm=etm;
        initComponents();
        this.nmmproj=nmmproj;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        comboEventTypes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEventsSummary = new javax.swing.JTable();
        buttonClose = new javax.swing.JButton();
        buttonExport = new javax.swing.JButton();
        comboIndicator = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        labelAverage = new javax.swing.JLabel();
        labelStandardDeviation = new javax.swing.JLabel();
        labelUncertaintyA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Select event type:");

        comboEventTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEventTypesActionPerformed(evt);
            }
        });

        tableEventsSummary.setModel(tm);
        tableEventsSummary.setColumnSelectionAllowed(true);
        tableEventsSummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEventsSummaryMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableEventsSummaryMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableEventsSummary);

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        buttonExport.setText("Export");
        buttonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportActionPerformed(evt);
            }
        });

        comboIndicator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Leq", "SEL" }));
        comboIndicator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIndicatorActionPerformed(evt);
            }
        });

        jLabel2.setText("Select indicator:");

        labelAverage.setText("Average = --,-");

        labelStandardDeviation.setText("Standard deviation = --,-");

        labelUncertaintyA.setText("Uncertainty A = --,-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                        .addComponent(buttonClose))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboIndicator, 0, 499, Short.MAX_VALUE)
                            .addComponent(comboEventTypes, 0, 499, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelAverage)
                        .addGap(18, 18, 18)
                        .addComponent(labelStandardDeviation)
                        .addGap(18, 18, 18)
                        .addComponent(labelUncertaintyA)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboEventTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAverage)
                    .addComponent(labelStandardDeviation)
                    .addComponent(labelUncertaintyA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClose)
                    .addComponent(buttonExport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (NMMEventType item : nmmproj.eventTypes) {
            this.comboEventTypes.addItem(item.toString());
            System.out.println("Dodaje kolejny ("+item.toString()+").");
        }

        this.tableEventsSummary.getValueAt(1,1);
    }//GEN-LAST:event_formWindowOpened

    private void comboEventTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEventTypesActionPerformed
        this.recalculateStatistics();
    }//GEN-LAST:event_comboEventTypesActionPerformed

    private void buttonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportActionPerformed

        int returnVal = fileChooser.showSaveDialog(this);
        boolean permission =false;

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (file.exists()) {
                if (JOptionPane.showConfirmDialog(this, "Do you want to overwrte selected file?","Selcted file exists!",
                        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                    permission=true;
                }
            } else {
                permission=true;
            }

            try {
                FileWriter fr = new FileWriter(file);
                BufferedWriter br = new BufferedWriter(fr);
                fr.write(tm.toString());
                fr.flush();
                fr.close();
            } catch(IOException e) {
                System.out.println("Eksport nie powiódł się :"+e.toString());
            }
        }        
    }//GEN-LAST:event_buttonExportActionPerformed

    private void comboIndicatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIndicatorActionPerformed
        this.recalculateStatistics();
    }//GEN-LAST:event_comboIndicatorActionPerformed

    private void recalculateStatistics() {
        //System.out.println("Wybieram:"+this.comboIndicator.getSelectedIndex()+1);
        tm.setIndicatorType(this.comboIndicator.getSelectedIndex()+1);
        tm.setEventType(new NMMEventType(this.comboEventTypes.getSelectedItem().toString()));
        tm.fireTableDataChanged();
        //super.paintComponents(super.getGraphics());
    }

    private void tableEventsSummaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEventsSummaryMouseClicked
        
    }//GEN-LAST:event_tableEventsSummaryMouseClicked

    private void tableEventsSummaryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEventsSummaryMouseReleased
         int selCol=this.tableEventsSummary.getSelectedColumn();
        if (selCol>2) {
            tm.setEventType(new NMMEventType(this.comboEventTypes.getSelectedItem().toString()));
            //super.paintComponents(super.getGraphics());
            this.labelStandardDeviation.setText("Standard deviation = "+NMMToolbox.formatDouble(
                    NMMNoiseCalculator.calculateStandardDeviation(
                    tm.getColumn(selCol))));
            this.labelAverage.setText("Average = "+NMMToolbox.formatDouble(
                    NMMNoiseCalculator.SredniaLog(tm.getColumn(selCol))));
            this.labelUncertaintyA.setText("Uncertainty A = "+NMMToolbox.formatDouble(
                    NMMNoiseCalculator.Lord95(tm.getColumn(selCol))));
        } else {
            this.labelStandardDeviation.setText("Standard deviation = ");
            this.labelAverage.setText("Average = --,-");
            this.labelUncertaintyA.setText("Uncertainty A = --,-");
        }

    }//GEN-LAST:event_tableEventsSummaryMouseReleased

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCloseActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonExport;
    private javax.swing.JComboBox comboEventTypes;
    private javax.swing.JComboBox comboIndicator;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAverage;
    private javax.swing.JLabel labelStandardDeviation;
    private javax.swing.JLabel labelUncertaintyA;
    private javax.swing.JTable tableEventsSummary;
    // End of variables declaration//GEN-END:variables

}
