/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NMMSetup.java
 *
 * Created on 2010-08-16, 01:41:31
 */

package nmm2010;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class NMMSetup extends javax.swing.JDialog {

    Setup nmmSetup;
    File currentProject;

    /** Creates new form NMMSetup */
    public NMMSetup(java.awt.Frame parent, boolean modal, Setup _nmmSetup, File _currentProject) {
        super(parent, modal);
        initComponents();
        nmmSetup=_nmmSetup;
        currentProject = _currentProject;
        this.jtextProjectPath.setText(nmmSetup.getProperty("NMM_SETUP_PROJECT_PATH", null));
        this.textUser.setText(nmmSetup.getProperty("NMM_SETUP_USER", null));
        this.textCompany.setText(nmmSetup.getProperty("NMM_SETUP_COMPANY", null));
        this.textLogoFile.setText(nmmSetup.getProperty("NMM_SETUP_LOGO", null));
        this.textNumberFormat.setText(nmmSetup.getProperty("NMM_SETUP_INTERFACE_NUMBERFORMAT", null));        
        
        //Czy selekcja ma być wyłączona po ustanowieniu zdarzenia?
        boolean tn=Boolean.parseBoolean(nmmSetup.getProperty("NMM_SETUP_CLEAR_SELECTION_AFTER_EVENT", null));
        this.checkboxClearSelectionAfterEvent.setSelected(tn);                
        //Czy ładować poprzedni projekt na starcie programu?
        tn=Boolean.parseBoolean(nmmSetup.getProperty("NMM_SETUP_LOAD_PREVIOUS_PROJECT_AT_STARTUP", null));
        this.boxLoadPreviousProject.setSelected(tn);                        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonCancel = new javax.swing.JButton();
        jbuttonSave = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtextProjectPath = new javax.swing.JTextField();
        jbuttonBrowse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textCompany = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textLogoFile = new javax.swing.JTextField();
        buttonBrowseLogo = new javax.swing.JButton();
        labelCompanyLogo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textPresentationsPath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textNumberFormat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboLanguage = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        checkboxDisplayLStart = new javax.swing.JCheckBox();
        checkboxDisplayLEnd = new javax.swing.JCheckBox();
        checkboxDisplayLMax = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        textSELCriteria = new javax.swing.JTextField();
        checkboxDisplayLMin = new javax.swing.JCheckBox();
        checkboxClearSelectionAfterEvent = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        boxLoadPreviousProject = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NMM Setup");
        setIconImage(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbuttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/Stop16.gif"))); // NOI18N
        jbuttonCancel.setText("Cancel");
        jbuttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCancelActionPerformed(evt);
            }
        });

        jbuttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/Save16.gif"))); // NOI18N
        jbuttonSave.setText("Save");
        jbuttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSaveActionPerformed(evt);
            }
        });

        jTabbedPane1.setToolTipText("Select tab to access required options.");

        jLabel2.setText("Project path:");

        jtextProjectPath.setText("c:\\");
            jtextProjectPath.setToolTipText("File chooser dialog default directory.");

            jbuttonBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/Open16.gif"))); // NOI18N
            jbuttonBrowse.setText("Browse");
            jbuttonBrowse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbuttonBrowseActionPerformed(evt);
                }
            });

            jLabel1.setText("User:");

            textUser.setText("user");
            textUser.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textUserActionPerformed(evt);
                }
            });

            jLabel3.setText("Company:");

            textCompany.setText("company");

            jLabel4.setText("Logo:");

            textLogoFile.setText("c:\\");

                buttonBrowseLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/Open16.gif"))); // NOI18N
                buttonBrowseLogo.setText("Browse");
                buttonBrowseLogo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        buttonBrowseLogoActionPerformed(evt);
                    }
                });

                labelCompanyLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                labelCompanyLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel10.setText("Presentations:");

                textPresentationsPath.setText("c:\\");
                    textPresentationsPath.setToolTipText("Indicate path where presentations will be written");

                    jButton1.setText("Browse");

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textPresentationsPath)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtextProjectPath, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbuttonBrowse))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(textLogoFile, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(buttonBrowseLogo))
                                        .addComponent(textCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addComponent(textUser, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addComponent(labelCompanyLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))))
                            .addContainerGap())
                    );
                    jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jtextProjectPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbuttonBrowse))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(textCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(textLogoFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonBrowseLogo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelCompanyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(textPresentationsPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addContainerGap(46, Short.MAX_VALUE))
                    );

                    jTabbedPane1.addTab("General", jPanel1);

                    jLabel6.setText("Number format:");

                    textNumberFormat.setText("#.000");

                    jLabel7.setText("# - optional fields, 0 - obligatory fields");

                    jLabel8.setText("Language:");

                    comboLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Polski", "English", "Deutsch", "Francais" }));

                    jLabel5.setText("During free selection display following parameters:");

                    checkboxDisplayLStart.setText("LStart");

                    checkboxDisplayLEnd.setText("LEnd");

                    checkboxDisplayLMax.setText("LMax");

                    jLabel9.setText("SEL criteria (difference in dB):");

                    textSELCriteria.setText("10");

                    checkboxDisplayLMin.setText("LMin");

                    checkboxClearSelectionAfterEvent.setText("clear selection after event creation");

                    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                    jPanel3.setLayout(jPanel3Layout);
                    jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textNumberFormat)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(comboLanguage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(checkboxDisplayLStart)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(checkboxDisplayLEnd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(checkboxDisplayLMax)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(checkboxDisplayLMin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textSELCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkboxClearSelectionAfterEvent)
                                        .addComponent(jLabel5))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())
                    );
                    jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(comboLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(textNumberFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(3, 3, 3)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkboxDisplayLStart)
                                .addComponent(checkboxDisplayLEnd)
                                .addComponent(checkboxDisplayLMax)
                                .addComponent(jLabel9)
                                .addComponent(textSELCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkboxDisplayLMin))
                            .addGap(18, 18, 18)
                            .addComponent(checkboxClearSelectionAfterEvent)
                            .addContainerGap(167, Short.MAX_VALUE))
                    );

                    jTabbedPane1.addTab("Interface", jPanel3);

                    boxLoadPreviousProject.setText("load previous project on startup");

                    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                    jPanel2.setLayout(jPanel2Layout);
                    jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(boxLoadPreviousProject)
                            .addContainerGap(315, Short.MAX_VALUE))
                    );
                    jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(boxLoadPreviousProject)
                            .addContainerGap(313, Short.MAX_VALUE))
                    );

                    jTabbedPane1.addTab("Start", jPanel2);

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jbuttonSave)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbuttonCancel))
                                .addComponent(jTabbedPane1))
                            .addContainerGap())
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTabbedPane1)
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbuttonCancel)
                                .addComponent(jbuttonSave))
                            .addContainerGap())
                    );

                    pack();
                }// </editor-fold>//GEN-END:initComponents

    private void jbuttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSaveActionPerformed
        this.nmmSetup.setProperty("NMM_SETUP_PROJECT_PATH", this.jtextProjectPath.getText());
        this.nmmSetup.setProperty("NMM_SETUP_COMPANY", this.textCompany.getText());
        this.nmmSetup.setProperty("NMM_SETUP_USER", this.textUser.getText());
        this.nmmSetup.setProperty("NMM_SETUP_LOGO", this.textLogoFile.getText());
        this.nmmSetup.setProperty("NMM_SETUP_INTERFACE_NUMBERFORMAT", this.textNumberFormat.getText());        
        this.nmmSetup.setProperty("NMM_SETUP_LANGUAGE", this.comboLanguage.getSelectedItem().toString());        
        this.nmmSetup.setProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LStart", String.valueOf(this.checkboxDisplayLStart.isSelected())); 
        this.nmmSetup.setProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LEnd", String.valueOf(this.checkboxDisplayLEnd.isSelected()));
        this.nmmSetup.setProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LMax", String.valueOf(this.checkboxDisplayLMax.isSelected()));
        this.nmmSetup.setProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LMin", String.valueOf(this.checkboxDisplayLMin.isSelected()));
        this.nmmSetup.setProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_SELCriteria", this.textSELCriteria.getText());
        this.nmmSetup.setProperty("NMM_SETUP_CLEAR_SELECTION_AFTER_EVENT", String.valueOf(this.checkboxClearSelectionAfterEvent.isSelected()));
        this.nmmSetup.setProperty("NMM_SETUP_LOAD_PREVIOUS_PROJECT_AT_STARTUP", String.valueOf(this.boxLoadPreviousProject.isSelected()));
        this.nmmSetup.setProperty("NMM_SETUP_PRESENTATIONSDIR", this.textPresentationsPath.getText());
        this.nmmSetup.setProperty("NMM_SETUP_PREVIOUS_PROJECT", this.currentProject.toString() );
        this.nmmSetup.saveNMMConfigurationToFile();
        JOptionPane.showMessageDialog(null,"Restart NMM in order to reload settings!","NMM 2010 * Information",JOptionPane.INFORMATION_MESSAGE);        
        this.dispose();
    }//GEN-LAST:event_jbuttonSaveActionPerformed

    private void jbuttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbuttonCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        String fileName=this.nmmSetup.getProperty("NMM_SETUP_LOGO", "ecoplan.png");
        File file = new File(fileName);
        this.textLogoFile.setText(file.getAbsolutePath());
        ImageIcon imgIcon = new ImageIcon(fileName);
        Image ni = imgIcon.getImage().getScaledInstance(200, 150, 1);
        ImageIcon smallImgIcon = new ImageIcon(ni);
        this.labelCompanyLogo.setIcon(smallImgIcon);
        this.labelCompanyLogo.setText("");
        this.comboLanguage.setSelectedItem(this.nmmSetup.getProperty("NMM_SETUP_LANGUAGE", "English"));
        
        String value="true";
        boolean result = value.equalsIgnoreCase(this.nmmSetup.getProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LMin", "true"));
        this.checkboxDisplayLMin.setSelected(result);
                
        result = value.equalsIgnoreCase(this.nmmSetup.getProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LMax", "true"));
        this.checkboxDisplayLMax.setSelected(result);
        
        result = value.equalsIgnoreCase(this.nmmSetup.getProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LEnd", "true"));
        this.checkboxDisplayLEnd.setSelected(result);
        
        result = value.equalsIgnoreCase(this.nmmSetup.getProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_LStart", "true"));
        this.checkboxDisplayLStart.setSelected(result);
                
        this.textSELCriteria.setText(this.nmmSetup.getProperty("NMM_SETUP_FREE_SELECTION_DISPLAY_SELCriteria", "10"));
        this.textPresentationsPath.setText(this.nmmSetup.getProperty("NMM_SETUP_PRESENTATIONSDIR", "c:\\"));
        
        result = value.equalsIgnoreCase(this.nmmSetup.getProperty("NMM_SETUP_LOAD_PREVIOUS_PROJECT_AT_STARTUP", "true"));
        this.boxLoadPreviousProject.setSelected(result);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void buttonBrowseLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowseLogoActionPerformed

        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            this.textLogoFile.setText(file.getAbsolutePath());
            this.nmmSetup.setProperty("NMM_SETUP_LOGO", file.getAbsolutePath());
        }
        String fileName = this.nmmSetup.getProperty("NMM_SETUP_LOGO", "ecoplan.png");
        ImageIcon imgIcon = new ImageIcon(fileName);
        Image ni = imgIcon.getImage().getScaledInstance(200, 150, 1);
        ImageIcon smallImgIcon = new ImageIcon(ni);
        this.labelCompanyLogo.setIcon(smallImgIcon);
        this.labelCompanyLogo.setText("");
    }//GEN-LAST:event_buttonBrowseLogoActionPerformed

    private void textUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserActionPerformed

   }//GEN-LAST:event_textUserActionPerformed

    private void jbuttonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonBrowseActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            this.jtextProjectPath.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jbuttonBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxLoadPreviousProject;
    private javax.swing.JButton buttonBrowseLogo;
    private javax.swing.JCheckBox checkboxClearSelectionAfterEvent;
    private javax.swing.JCheckBox checkboxDisplayLEnd;
    private javax.swing.JCheckBox checkboxDisplayLMax;
    private javax.swing.JCheckBox checkboxDisplayLMin;
    private javax.swing.JCheckBox checkboxDisplayLStart;
    private javax.swing.JComboBox comboLanguage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbuttonBrowse;
    private javax.swing.JButton jbuttonCancel;
    private javax.swing.JButton jbuttonSave;
    private javax.swing.JTextField jtextProjectPath;
    private javax.swing.JLabel labelCompanyLogo;
    private javax.swing.JTextField textCompany;
    private javax.swing.JTextField textLogoFile;
    private javax.swing.JTextField textNumberFormat;
    private javax.swing.JTextField textPresentationsPath;
    private javax.swing.JTextField textSELCriteria;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables

}
