/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NMMValuesEditor.java
 *
 * Created on 2011-02-18, 11:05:19
 */

package biz.ekoplan.nmm2010.val_ed;

import biz.ekoplan.nmm2010.enums.RecordValueType;
import javax.swing.table.DefaultTableModel;
import biz.ekoplan.nmm2010.measurement.NMMMeasurement;
import nmm2010.NMMEvent;
import nmm2010.NMMProject;

/**
 *
 * @author Ecoplan
 */
public class NMMValuesEditor extends javax.swing.JDialog {

    DefaultTableModel dtm;
    NMMProject nmmProj;

    /** Creates new form NMMValuesEditor */
    public NMMValuesEditor(java.awt.Frame parent, boolean modal, DefaultTableModel _dtm, NMMProject _nmmProj) {
        
        super(parent, modal);
        dtm=_dtm;
        this.nmmProj=_nmmProj;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelOperationButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        textAddValue = new javax.swing.JTextField();
        panelButtons = new javax.swing.JPanel();
        buttonExport = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jTable1.setModel(this.dtm);
        jTable1.setToolTipText("Current measurement selected values.");
        jTable1.setCellSelectionEnabled(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        panelOperationButtons.setLayout(new javax.swing.BoxLayout(panelOperationButtons, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("add value :");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelOperationButtons.add(jButton1);

        textAddValue.setText("0");
        panelOperationButtons.add(textAddValue);

        jPanel1.add(panelOperationButtons);

        getContentPane().add(jPanel1);

        panelButtons.setLayout(new javax.swing.BoxLayout(panelButtons, javax.swing.BoxLayout.LINE_AXIS));

        buttonExport.setText("Export");
        buttonExport.setToolTipText("Export values to text file.");
        panelButtons.add(buttonExport);

        buttonCancel.setText("Cancel");
        buttonCancel.setToolTipText("Discard changes and quit.");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        panelButtons.add(buttonCancel);

        buttonOK.setText("OK");
        buttonOK.setToolTipText("Accept changes and quit.");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        panelButtons.add(buttonOK);

        getContentPane().add(panelButtons);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed

        NMMEvent ev;
        ev=this.nmmProj.getCurrentSelection();
        NMMMeasurement ms;
        ms=this.nmmProj.getCurrentMeasurement();

        int recNumb=(int)(ev.getMilisLength()/this.nmmProj.getProjectTimeResolution());
        int firstRec = ms.getRecordIndex(ev.getStart());
        for (int i=0; i<recNumb; i++) { 
            String nSVal = (String)dtm.getValueAt(i,0);
            double nVal = Double.parseDouble(nSVal.replaceAll(",", "."));
            ms.setRecordValue(firstRec+i, nVal, RecordValueType.LAeq);
        }
        this.nmmProj.setSaved(false);
        this.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NMMEvent ev;
        ev=this.nmmProj.getCurrentSelection();
        NMMMeasurement ms;
        ms=this.nmmProj.getCurrentMeasurement();

        int recNumb=(int)(ev.getMilisLength()/this.nmmProj.getProjectTimeResolution());
        int firstRec = ms.getRecordIndex(ev.getStart());
        for (int i=0; i<recNumb; i++) {
            String nSVal = (String)dtm.getValueAt(i,0);
            double nVal = Double.parseDouble(nSVal.replaceAll(",", "."));
            nVal=nVal+Double.parseDouble(this.textAddValue.getText());
            dtm.setValueAt(String.valueOf(nVal),i,0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonExport;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelOperationButtons;
    private javax.swing.JTextField textAddValue;
    // End of variables declaration//GEN-END:variables

}
