/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package biz.ekoplan.nmm2010.surcemodel.sminterface;

import biz.ekoplan.nmm2010.nmmproject.NMMProjectModelsChanged;
import biz.ekoplan.nmm2010.nmmproject.NMMProjectModelsListener;
import biz.ekoplan.nmm2010.reports.NMMReportWriter;
import biz.ekoplan.nmm2010.surcemodel.NMMNoiseSourceModel;
import biz.ekoplan.nmm2010.surcemodel.NMMNoiseSourceModelChangedListener;
import biz.ekoplan.nmm2010.surcemodel.NMMPointLocationTableModel;
import biz.ekoplan.nmm2010.surcemodel.NMMSingleEventsMethodModel;
import biz.ekoplan.nmm2010.surcemodel.NMMSoundPowerLevelModel;
import biz.ekoplan.nmm2010.toolbox.NMMToolbox;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import nmm2010.NMMProject;
import nmm2010.Setup;

/**
 * 
 * @author Jarek
 */
public class NMMSoundPowerLevelModelInterface extends javax.swing.JDialog 
    implements NMMProjectModelsListener, NMMAbstractNoiseSourceModelInterface,
    NMMNoiseSourceModelChangedListener{

    NMMSoundPowerLevelModel calculationModel;
    Setup setup;
    NMMProject nmmProject;
    NMMPointLocationTableModel pltm;
    BufferedImage imgMap;
    
    /**
     * Creates new form NMMSoundPowerLevelModelInterface
     * @param parent
     * @param modal
     * @param _splm
     * @param _stp
     * @param _nmmProj
     * @param _pltm
     */
    public NMMSoundPowerLevelModelInterface(java.awt.Frame parent, boolean modal,
            NMMSoundPowerLevelModel _splm, Setup _stp, NMMProject _nmmProj,
            NMMPointLocationTableModel _pltm) {
        
        super(parent, modal);
        
        this.calculationModel=_splm;
        this.setup=_stp;
        this.nmmProject=_nmmProj;
        this.pltm=_pltm;
                        
        initComponents();                
            
        //trzeba zainicjalizować zawartośc list rozwijalnych, które mają 
        //służyć jako edytory w tabeli
         setUpEventTypesColumn();
        
        
        this.tablePointsData.setModel(pltm);
        this.tablePointsData.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(this.comboEventTypeChooserBackground));
        this.tablePointsData.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(this.comboEventTypeChooserSource));
        
        this.calculationModel.rearrangeDataTable();
        this.calculationModel.recalculateModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEventTypeChooserSource = new javax.swing.JComboBox();
        comboEventTypeChooserBackground = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        butonOK = new javax.swing.JButton();
        panelWarnings = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        textCalculationModelName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNoiseSourceName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textNoiseSourceType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNoiseSourceModel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textSoundSourceDimensions = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textSoundSourceManufacturer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textSoundSourceYear = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textSoundSourceSerialNumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textNoiseSourceWorkingConditions = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textNoiseSourceMounting = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        textNoiseSourceInMeasurementEnvironment = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        textNoiseSourceWorkDuringMeasurement = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textWarnings = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        comboMeasurementSurfaceType = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboNumberReflectiveSurfaces = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        textRefBox_l1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textRefBox_l2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textRefBox_l3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textMeasurementDistance = new javax.swing.JTextField();
        labelS = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboMeasurementEnvironment = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        textClosedSpaceDim_l1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textClosedSpaceDim_l2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textClosedSpaceDim_l3 = new javax.swing.JTextField();
        labelK2A = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePointsData = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        textAlpha = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        textMeasurementTime = new javax.swing.JTextField();
        labelK1A = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panelMap = new javax.swing.JPanel();
        labelMap = new javax.swing.JLabel();
        buttonCreateCalculationReport = new javax.swing.JButton();
        labelFinalSPL = new javax.swing.JLabel();

        comboEventTypeChooserSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEventTypeChooserSource.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboEventTypeChooserSourceFocusLost(evt);
            }
        });

        comboEventTypeChooserBackground.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEventTypeChooserBackground.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboEventTypeChooserBackgroundFocusLost(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Sound power level according to PN-EN ISO 3746:2011");

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        butonOK.setText("OK");
        butonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOKActionPerformed(evt);
            }
        });

        jLabel23.setText("Model name:");

        textCalculationModelName.setText("Sound power level calculation model.");
        textCalculationModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCalculationModelNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCalculationModelName, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(textCalculationModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
        );

        panelWarnings.addTab("Calculation model", jPanel3);

        jLabel2.setText("Sound source description");

        jLabel3.setText("Name:");

        textNoiseSourceName.setText("Wentylator nadmuchu 1");
        textNoiseSourceName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNoiseSourceNameFocusLost(evt);
            }
        });
        textNoiseSourceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNoiseSourceNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Type:");

        textNoiseSourceType.setText("WN 234");
        textNoiseSourceType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNoiseSourceTypeFocusLost(evt);
            }
        });

        jLabel5.setText("Model:");

        textNoiseSourceModel.setText("23/243/WA");
        textNoiseSourceModel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNoiseSourceModelFocusLost(evt);
            }
        });

        jLabel6.setText("Dimensions:");

        textSoundSourceDimensions.setText("1 x 1 x 1,5m");
        textSoundSourceDimensions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSoundSourceDimensionsFocusLost(evt);
            }
        });
        textSoundSourceDimensions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSoundSourceDimensionsActionPerformed(evt);
            }
        });

        jLabel7.setText("Manufacturer:");

        textSoundSourceManufacturer.setText("Azarex Ltd.");
        textSoundSourceManufacturer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSoundSourceManufacturerFocusLost(evt);
            }
        });
        textSoundSourceManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSoundSourceManufacturerActionPerformed(evt);
            }
        });

        jLabel8.setText("Year:");

        textSoundSourceYear.setText("1982");
        textSoundSourceYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSoundSourceYearFocusLost(evt);
            }
        });

        jLabel9.setText("Serial number:");

        textSoundSourceSerialNumber.setText("197AS/AAA/397");
        textSoundSourceSerialNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSoundSourceSerialNumberFocusLost(evt);
            }
        });
        textSoundSourceSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSoundSourceSerialNumberActionPerformed(evt);
            }
        });

        jLabel16.setText("Noise source working conditions:");

        textNoiseSourceWorkingConditions.setText("Praca w typowych warunkach.");
        textNoiseSourceWorkingConditions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNoiseSourceWorkingConditionsFocusLost(evt);
            }
        });

        jLabel21.setText("Noise source mounting:");

        textNoiseSourceMounting.setText("Urządzenie zamontowane w sposób docelowy.");
        textNoiseSourceMounting.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNoiseSourceMountingFocusLost(evt);
            }
        });

        jLabel26.setText("Noise source in measurement environment:");

        textNoiseSourceInMeasurementEnvironment.setText("Nie wiem co to znaczy?!");
        textNoiseSourceInMeasurementEnvironment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNoiseSourceInMeasurementEnvironmentFocusLost(evt);
            }
        });

        jLabel27.setText("Noise source work during measurement:");

        textNoiseSourceWorkDuringMeasurement.setText("Źródło hałasu pracuje w sposób typowy dla codziennej pracy.");
        textNoiseSourceWorkDuringMeasurement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNoiseSourceWorkDuringMeasurementFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSoundSourceDimensions))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSoundSourceManufacturer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSoundSourceYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSoundSourceSerialNumber))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNoiseSourceWorkingConditions))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNoiseSourceMounting))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNoiseSourceInMeasurementEnvironment))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNoiseSourceWorkDuringMeasurement, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNoiseSourceName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNoiseSourceType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNoiseSourceModel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textNoiseSourceInMeasurementEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNoiseSourceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(textNoiseSourceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(textNoiseSourceModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textSoundSourceDimensions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textSoundSourceManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textSoundSourceYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(textSoundSourceSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(textNoiseSourceWorkingConditions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(textNoiseSourceMounting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(textNoiseSourceWorkDuringMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelWarnings.addTab("Sound source and measurement conditions", jPanel1);

        textWarnings.setColumns(20);
        textWarnings.setRows(5);
        jScrollPane2.setViewportView(textWarnings);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelWarnings.addTab("Warnings!", jPanel4);

        comboMeasurementSurfaceType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Parallelepiped", "Spherical" }));
        comboMeasurementSurfaceType.setEnabled(false);
        comboMeasurementSurfaceType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeasurementSurfaceTypeActionPerformed(evt);
            }
        });

        jLabel10.setText("Measurement surface:");

        jLabel11.setText("Number of reflective surfaces:");

        comboNumberReflectiveSurfaces.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 (floor)", "2 (floor + 1 wall)", "3 (floor + 2 walls)" }));
        comboNumberReflectiveSurfaces.setEnabled(false);
        comboNumberReflectiveSurfaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumberReflectiveSurfacesActionPerformed(evt);
            }
        });

        jLabel12.setText("Dimension of reference box [m]:    l1=");

        textRefBox_l1.setText("1");
        textRefBox_l1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textRefBox_l1FocusLost(evt);
            }
        });
        textRefBox_l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRefBox_l1ActionPerformed(evt);
            }
        });

        jLabel13.setText("[m]      l2=");

        textRefBox_l2.setText("1");
        textRefBox_l2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textRefBox_l2FocusLost(evt);
            }
        });
        textRefBox_l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRefBox_l2ActionPerformed(evt);
            }
        });

        jLabel14.setText("[m]      l3 (h)=");

        textRefBox_l3.setText("1");
        textRefBox_l3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textRefBox_l3FocusLost(evt);
            }
        });
        textRefBox_l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRefBox_l3ActionPerformed(evt);
            }
        });

        jLabel15.setText("Measurement distance d[m] =");

        textMeasurementDistance.setText("1");
        textMeasurementDistance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textMeasurementDistanceFocusLost(evt);
            }
        });

        labelS.setText("Measurement surface area [sq. m] =  --,--");

        jLabel17.setText("[s]      Environment:");

        comboMeasurementEnvironment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Open space", "Closed space" }));
        comboMeasurementEnvironment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeasurementEnvironmentActionPerformed(evt);
            }
        });

        jLabel18.setText("Closed space dimensions:  l1=");

        textClosedSpaceDim_l1.setText("1");
        textClosedSpaceDim_l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClosedSpaceDim_l1ActionPerformed(evt);
            }
        });

        jLabel19.setText("l2=");

        textClosedSpaceDim_l2.setText("1");
        textClosedSpaceDim_l2.setMinimumSize(new java.awt.Dimension(36, 20));
        textClosedSpaceDim_l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClosedSpaceDim_l2ActionPerformed(evt);
            }
        });

        jLabel20.setText("l3=");

        textClosedSpaceDim_l3.setText("1");
        textClosedSpaceDim_l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClosedSpaceDim_l3ActionPerformed(evt);
            }
        });

        labelK2A.setText("K2A =  --,--");

        jLabel22.setText("Measurement points:");

        tablePointsData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Point", "X[m]", "Y[m]", "Z[m]", "BNL", "NL"
            }
        ));
        tablePointsData.setRowHeight(20);
        tablePointsData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablePointsDataFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tablePointsData);

        jLabel24.setText("Alpha =");

        textAlpha.setText("1");

        jLabel25.setText("t0 =");

        textMeasurementTime.setText("10");
        textMeasurementTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMeasurementTimeActionPerformed(evt);
            }
        });

        labelK1A.setText("K1A = --,-");

        jLabel28.setText("[m]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboMeasurementSurfaceType, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNumberReflectiveSurfaces, 0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMeasurementTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMeasurementEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textClosedSpaceDim_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textClosedSpaceDim_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addGap(11, 11, 11)
                                .addComponent(textClosedSpaceDim_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textRefBox_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textRefBox_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(2, 2, 2)
                                .addComponent(textRefBox_l3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelK1A)
                                .addGap(18, 18, 18)
                                .addComponent(labelK2A)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMeasurementDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelS)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAlpha)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMeasurementSurfaceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(comboNumberReflectiveSurfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textRefBox_l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(textRefBox_l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(textRefBox_l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(textMeasurementDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelS))
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(textAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(comboMeasurementEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(textClosedSpaceDim_l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(textClosedSpaceDim_l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(textClosedSpaceDim_l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(textMeasurementTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK1A)
                    .addComponent(labelK2A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        panelWarnings.addTab("Acoustic data", jPanel2);

        panelMap.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panelMapComponentResized(evt);
            }
        });

        labelMap.setForeground(new java.awt.Color(255, 255, 255));
        labelMap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelMapLayout = new javax.swing.GroupLayout(panelMap);
        panelMap.setLayout(panelMapLayout);
        panelMapLayout.setHorizontalGroup(
            panelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMap, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMapLayout.setVerticalGroup(
            panelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMap, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelWarnings.addTab("Situation", panelMap);

        buttonCreateCalculationReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/History16.gif"))); // NOI18N
        buttonCreateCalculationReport.setText("Report");
        buttonCreateCalculationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateCalculationReportActionPerformed(evt);
            }
        });

        labelFinalSPL.setText("Sound Power Level LW = --,- dB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWarnings)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCreateCalculationReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFinalSPL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelWarnings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(butonOK)
                    .addComponent(buttonCreateCalculationReport)
                    .addComponent(labelFinalSPL))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setUpEventTypesColumn() {
        
        this.comboEventTypeChooserBackground.removeAllItems();
        this.comboEventTypeChooserSource.removeAllItems();
        for (Object eventType : this.nmmProject.getEventTypes()) {
            this.comboEventTypeChooserBackground.addItem(eventType);
            this.comboEventTypeChooserSource.addItem(eventType);
        }        
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
       //po utworzeniu obiektu okna, dodajemy go jako słuchacza do modelu
       //obliczeniowego źródła hałasu
       this.calculationModel.addNoiseSourceModelChangedListener(this);
       
       
    }//GEN-LAST:event_formWindowOpened

    private void butonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOKActionPerformed
        
        this.calculationModel.setModelName(this.textCalculationModelName.getText());
        //if calculation model isn't in the project yet, than add it
        if (!this.nmmProject.contains(calculationModel)) {                    
            System.out.println("Tego modelu źródła jeszcze nie ma, dodaję ...");
            this.nmmProject.addNoiseSourceModel(this.calculationModel);
        }
        this.dispose();
    }//GEN-LAST:event_butonOKActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textRefBox_l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRefBox_l1ActionPerformed
      
    }//GEN-LAST:event_textRefBox_l1ActionPerformed

    private void textRefBox_l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRefBox_l2ActionPerformed
        
    }//GEN-LAST:event_textRefBox_l2ActionPerformed

    private void textRefBox_l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRefBox_l3ActionPerformed
    }//GEN-LAST:event_textRefBox_l3ActionPerformed

    private void comboMeasurementSurfaceTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeasurementSurfaceTypeActionPerformed
        this.updateNoiseModel();
    }//GEN-LAST:event_comboMeasurementSurfaceTypeActionPerformed

    private void textRefBox_l1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRefBox_l1FocusLost
        this.updateNoiseModel();
    }//GEN-LAST:event_textRefBox_l1FocusLost

    private void textRefBox_l2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRefBox_l2FocusLost
        
        
    }//GEN-LAST:event_textRefBox_l2FocusLost

    private void textRefBox_l3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRefBox_l3FocusLost
        this.updateNoiseModel();
    }//GEN-LAST:event_textRefBox_l3FocusLost

    private void textClosedSpaceDim_l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClosedSpaceDim_l1ActionPerformed
        this.calculationModel.setClosedSpaceDimensionL1(Double.valueOf(this.textClosedSpaceDim_l1.getText()));
    }//GEN-LAST:event_textClosedSpaceDim_l1ActionPerformed

    private void textClosedSpaceDim_l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClosedSpaceDim_l2ActionPerformed
        this.updateNoiseModel();
    }//GEN-LAST:event_textClosedSpaceDim_l2ActionPerformed

    private void textClosedSpaceDim_l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClosedSpaceDim_l3ActionPerformed
        this.updateNoiseModel();
    }//GEN-LAST:event_textClosedSpaceDim_l3ActionPerformed

    private void comboMeasurementEnvironmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeasurementEnvironmentActionPerformed
        if (this.comboMeasurementEnvironment.getSelectedIndex()==0) {
            //środowisko pomiarowe otwarte (na dworze)
            //wyłączamy kontrolki definiujące pomieszczenie pomiarowe
            this.textClosedSpaceDim_l1.setEnabled(false);
            this.textClosedSpaceDim_l2.setEnabled(false);
            this.textClosedSpaceDim_l3.setEnabled(false);            
        } else {
            //środowisko pomiarowe zamknięte (pomieszczenie)
            //włączamy kontrolki definiujące pomieszczenie pomiarowe
            this.textClosedSpaceDim_l1.setEnabled(true);
            this.textClosedSpaceDim_l2.setEnabled(true);
            this.textClosedSpaceDim_l3.setEnabled(true);
        }
        this.updateNoiseModel();
    }//GEN-LAST:event_comboMeasurementEnvironmentActionPerformed

    private void textMeasurementTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMeasurementTimeActionPerformed
        this.updateNoiseModel();
    }//GEN-LAST:event_textMeasurementTimeActionPerformed

    private void textMeasurementDistanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMeasurementDistanceFocusLost
        this.updateNoiseModel();
    }//GEN-LAST:event_textMeasurementDistanceFocusLost

    private void comboEventTypeChooserSourceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboEventTypeChooserSourceFocusLost
        
    }//GEN-LAST:event_comboEventTypeChooserSourceFocusLost

    private void comboEventTypeChooserBackgroundFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboEventTypeChooserBackgroundFocusLost
        
    }//GEN-LAST:event_comboEventTypeChooserBackgroundFocusLost

    private void tablePointsDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablePointsDataFocusLost
        this.calculationModel.recalculateModel();
    }//GEN-LAST:event_tablePointsDataFocusLost

    private void updateNoiseModel() {
        
        this.calculationModel.setMeasurementTime(Double.valueOf(this.textMeasurementTime.getText()));
        
        this.calculationModel.setClosedSpaceDimensionL3(Double.valueOf(this.textClosedSpaceDim_l3.getText()));
        this.calculationModel.setClosedSpaceDimensionL2(Double.valueOf(this.textClosedSpaceDim_l2.getText()));
        
        this.calculationModel.setMeasurementDistance(Double.valueOf(this.textMeasurementDistance.getText()));
        
        this.calculationModel.setRefBox_l1(Double.valueOf(this.textRefBox_l1.getText()));
        this.calculationModel.setRefBox_l2(Double.valueOf(this.textRefBox_l2.getText()));
        this.calculationModel.setRefBox_l3(Double.valueOf(this.textRefBox_l3.getText()));
        
        this.calculationModel.setMeasurementSurfaceType(this.comboMeasurementSurfaceType.getSelectedIndex());
        
        this.calculationModel.setMeasurementSpace(this.comboMeasurementEnvironment.getSelectedIndex());
        
        this.redrawMap();
    }
    
    private void buttonCreateCalculationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateCalculationReportActionPerformed
        
        NMMReportWriter rw;
        rw = new NMMReportWriter(this.setup, this.calculationModel);        
        rw.writeReport();
    }//GEN-LAST:event_buttonCreateCalculationReportActionPerformed

    private void textCalculationModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCalculationModelNameActionPerformed
        this.calculationModel.setModelName(this.textCalculationModelName.getText());
    }//GEN-LAST:event_textCalculationModelNameActionPerformed

    private void textNoiseSourceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNoiseSourceNameActionPerformed

    }//GEN-LAST:event_textNoiseSourceNameActionPerformed

    private void textSoundSourceSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoundSourceSerialNumberActionPerformed
        
    }//GEN-LAST:event_textSoundSourceSerialNumberActionPerformed

    private void textSoundSourceManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoundSourceManufacturerActionPerformed

    }//GEN-LAST:event_textSoundSourceManufacturerActionPerformed

    private void textSoundSourceDimensionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoundSourceDimensionsActionPerformed
        
    }//GEN-LAST:event_textSoundSourceDimensionsActionPerformed

    private void textNoiseSourceNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNoiseSourceNameFocusLost
        this.calculationModel.setSoundSourceName(this.textNoiseSourceName.getText());
    }//GEN-LAST:event_textNoiseSourceNameFocusLost

    private void textNoiseSourceTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNoiseSourceTypeFocusLost
        this.calculationModel.setSoundSourceType(this.textNoiseSourceType.getText());
    }//GEN-LAST:event_textNoiseSourceTypeFocusLost

    private void textNoiseSourceModelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNoiseSourceModelFocusLost
        this.calculationModel.setSoundSourceModel(this.textNoiseSourceModel.getText());
    }//GEN-LAST:event_textNoiseSourceModelFocusLost

    private void textSoundSourceDimensionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSoundSourceDimensionsFocusLost
        this.calculationModel.setSoundSourceDimension(this.textSoundSourceDimensions.getText());        
    }//GEN-LAST:event_textSoundSourceDimensionsFocusLost

    private void textSoundSourceManufacturerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSoundSourceManufacturerFocusLost
        this.calculationModel.setSoundSourceManufacturer(this.textSoundSourceManufacturer.getText());
    }//GEN-LAST:event_textSoundSourceManufacturerFocusLost

    private void textSoundSourceYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSoundSourceYearFocusLost
        this.calculationModel.setSoundSourceYear(this.textSoundSourceYear.getText());
    }//GEN-LAST:event_textSoundSourceYearFocusLost

    private void textSoundSourceSerialNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSoundSourceSerialNumberFocusLost
        this.calculationModel.setSoundSourceSerialNumber(this.textSoundSourceSerialNumber.getText());
    }//GEN-LAST:event_textSoundSourceSerialNumberFocusLost

    private void textNoiseSourceWorkingConditionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNoiseSourceWorkingConditionsFocusLost
        this.calculationModel.setNoiseSourceWorkingConditions(this.textNoiseSourceWorkingConditions.getText());
    }//GEN-LAST:event_textNoiseSourceWorkingConditionsFocusLost

    private void textNoiseSourceMountingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNoiseSourceMountingFocusLost
        this.calculationModel.setNoiseSourceMounting(this.textNoiseSourceMounting.getText());
    }//GEN-LAST:event_textNoiseSourceMountingFocusLost

    private void textNoiseSourceInMeasurementEnvironmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNoiseSourceInMeasurementEnvironmentFocusLost
        this.calculationModel.setMeasurementEnvironment(this.textNoiseSourceInMeasurementEnvironment.getText());
    }//GEN-LAST:event_textNoiseSourceInMeasurementEnvironmentFocusLost

    private void textNoiseSourceWorkDuringMeasurementFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNoiseSourceWorkDuringMeasurementFocusLost
        this.calculationModel.setNoiseSourceWorkDuringMeasurement(this.textNoiseSourceWorkDuringMeasurement.getText());
    }//GEN-LAST:event_textNoiseSourceWorkDuringMeasurementFocusLost

    private void comboNumberReflectiveSurfacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumberReflectiveSurfacesActionPerformed
        
        switch (this.comboNumberReflectiveSurfaces.getSelectedIndex()) {
        case 0:
            this.calculationModel.setNumberOfReflectiveSurfaces(1);
            break;
        case 1:
            this.calculationModel.setNumberOfReflectiveSurfaces(2);
            break;
        case 2:
            this.calculationModel.setNumberOfReflectiveSurfaces(3);
            break;
        }        
    }//GEN-LAST:event_comboNumberReflectiveSurfacesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.tablePointsData.setModel(new DefaultTableModel());
    }//GEN-LAST:event_formWindowClosed

    private void panelMapComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelMapComponentResized
                
    }//GEN-LAST:event_panelMapComponentResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        this.redrawMap();
    }//GEN-LAST:event_formComponentResized
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonOK;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreateCalculationReport;
    private javax.swing.JComboBox comboEventTypeChooserBackground;
    private javax.swing.JComboBox comboEventTypeChooserSource;
    private javax.swing.JComboBox comboMeasurementEnvironment;
    private javax.swing.JComboBox comboMeasurementSurfaceType;
    private javax.swing.JComboBox comboNumberReflectiveSurfaces;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFinalSPL;
    private javax.swing.JLabel labelK1A;
    private javax.swing.JLabel labelK2A;
    private javax.swing.JLabel labelMap;
    private javax.swing.JLabel labelS;
    private javax.swing.JPanel panelMap;
    private javax.swing.JTabbedPane panelWarnings;
    private javax.swing.JTable tablePointsData;
    private javax.swing.JTextField textAlpha;
    private javax.swing.JTextField textCalculationModelName;
    private javax.swing.JTextField textClosedSpaceDim_l1;
    private javax.swing.JTextField textClosedSpaceDim_l2;
    private javax.swing.JTextField textClosedSpaceDim_l3;
    private javax.swing.JTextField textMeasurementDistance;
    private javax.swing.JTextField textMeasurementTime;
    private javax.swing.JTextField textNoiseSourceInMeasurementEnvironment;
    private javax.swing.JTextField textNoiseSourceModel;
    private javax.swing.JTextField textNoiseSourceMounting;
    private javax.swing.JTextField textNoiseSourceName;
    private javax.swing.JTextField textNoiseSourceType;
    private javax.swing.JTextField textNoiseSourceWorkDuringMeasurement;
    private javax.swing.JTextField textNoiseSourceWorkingConditions;
    private javax.swing.JTextField textRefBox_l1;
    private javax.swing.JTextField textRefBox_l2;
    private javax.swing.JTextField textRefBox_l3;
    private javax.swing.JTextField textSoundSourceDimensions;
    private javax.swing.JTextField textSoundSourceManufacturer;
    private javax.swing.JTextField textSoundSourceSerialNumber;
    private javax.swing.JTextField textSoundSourceYear;
    private javax.swing.JTextArea textWarnings;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispatchNMMProjectModelsChanged(NMMProjectModelsChanged _mEvent) {
        System.out.println("Zmieniło sie cos w zawartości modeli projektu, ale akurat nie jestem zainteresowany...");
    }

    @Override
    public void dispatchNMMNoiseSourceModelChanged(NMMNoiseSourceModel _mEvent) {
        System.out.println("Aktualizuję wyniki modelu na interfejsie ...");        
        this.labelFinalSPL.setText("Sound Power Level LW = "+NMMToolbox.formatDouble(this.calculationModel.getSoundPowerLevel())+" dB");
        this.labelS.setText("Measurement surface area [sq. m] = "+this.calculationModel.getMeasurementSurfaceArea());
        this.labelK1A.setText("K1A = "+this.calculationModel.getK1A());
        this.labelK2A.setText("K2A = "+this.calculationModel.getK2A());
        this.textWarnings.setText(this.calculationModel.getWarnings());                
    }

    @Override
    public boolean isComplete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * Redraws image showing location of measurement points on measurement surface
     * according to PN-EN ISO 3746:2011
     */
    private void redrawMap() {
       
        this.imgMap= this.calculationModel.getMeasurementPointsMap(this.labelMap.getWidth(), this.labelMap.getHeight());        
        this.labelMap.setIcon(new ImageIcon(imgMap));
    }
}
