/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package biz.ekoplan.nmm2010.surcemodel.sminterface;

import biz.ekoplan.nmm2010.enums.NoiseLevelIndicators;
import biz.ekoplan.nmm2010.nmmproject.NMMProjectModelsChanged;
import biz.ekoplan.nmm2010.nmmproject.NMMProjectModelsListener;
import biz.ekoplan.nmm2010.surcemodel.NMMNoiseSourceModel;
import biz.ekoplan.nmm2010.surcemodel.NMMNoiseSourceModelChangedListener;
import biz.ekoplan.nmm2010.surcemodel.NMMNoiseWallAttenuationModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jarek
 */
public class NMMWallAttenuationInterface extends javax.swing.JDialog 
    implements NMMProjectModelsListener, NMMAbstractNoiseSourceModelInterface,
    NMMNoiseSourceModelChangedListener{

    NMMNoiseWallAttenuationModel nmmNoiseWallAttenuationModel;
    
    /**
     * Creates new form NMMWallAttenuationInterface
     * @param parent
     * @param modal
     */
    public NMMWallAttenuationInterface(java.awt.Frame parent, boolean modal,
            NMMNoiseWallAttenuationModel _nwam) {
        
        super(parent, modal);
        this.nmmNoiseWallAttenuationModel=_nwam;
        initComponents();
        
        DefaultComboBoxModel cbmMeasBefRef;
        DefaultComboBoxModel cbmMeasBefImi;
        DefaultComboBoxModel cbmMeasAftRef;
        DefaultComboBoxModel cbmMeasAftImi;
        DefaultComboBoxModel cbmEventBefRef;
        DefaultComboBoxModel cbmEventBefImi;
        DefaultComboBoxModel cbmEventAftRef;
        DefaultComboBoxModel cbmEventAftImi;
                
        cbmMeasBefRef = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getAllMeasurements().toArray());
        cbmMeasBefImi = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getAllMeasurements().toArray());
        cbmMeasAftRef = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getAllMeasurements().toArray());
        cbmMeasAftImi = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getAllMeasurements().toArray());
        this.comboMeasurementBeforeReference.setModel(cbmMeasBefRef);
        this.comboMeasurementBeforeImision.setModel(cbmMeasBefRef);
        this.comboMeasurementAfterReference.setModel(cbmMeasBefRef);
        this.comboMeasurementAfterImision.setModel(cbmMeasBefRef);
        
        cbmEventBefRef = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getEventTypes());
        cbmEventBefImi = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getEventTypes());
        cbmEventAftRef = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getEventTypes());
        cbmEventAftImi = new DefaultComboBoxModel(this.nmmNoiseWallAttenuationModel.getProject().getEventTypes());
        this.comboEventsBeforeReference.setModel(cbmEventBefRef);
        this.comboEventsBeforeImision.setModel(cbmEventBefImi);
        this.comboEventsAfterReference.setModel(cbmEventAftRef);
        this.comboEventsAfterImision.setModel(cbmEventAftImi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboMeasurementBeforeReference = new javax.swing.JComboBox();
        comboMeasurementBeforeImision = new javax.swing.JComboBox();
        comboMeasurementAfterReference = new javax.swing.JComboBox();
        comboMeasurementAfterImision = new javax.swing.JComboBox();
        comboEventsBeforeReference = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboEventsBeforeImision = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboEventsAfterReference = new javax.swing.JComboBox();
        comboEventsAfterImision = new javax.swing.JComboBox();
        labelNoiseWallEfficiencyLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboFieldType = new javax.swing.JComboBox();
        labelNoiseWallEfficiency = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textCalculationModelName = new javax.swing.JTextField();
        buttonCalculationReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(0, 0, 255));
        labelHeader.setText("Noise walls attenuation according to PN EN 10847:2002");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Before installation");

        jLabel3.setText("Reference point");

        jLabel4.setText("Imision point");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("After installation");

        jLabel6.setText("Reference point");

        jLabel7.setText("Imision point");

        comboMeasurementBeforeReference.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMeasurementBeforeReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeasurementBeforeReferenceActionPerformed(evt);
            }
        });

        comboMeasurementBeforeImision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMeasurementBeforeImision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeasurementBeforeImisionActionPerformed(evt);
            }
        });

        comboMeasurementAfterReference.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMeasurementAfterReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeasurementAfterReferenceActionPerformed(evt);
            }
        });

        comboMeasurementAfterImision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMeasurementAfterImision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeasurementAfterImisionActionPerformed(evt);
            }
        });

        comboEventsBeforeReference.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEventsBeforeReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEventsBeforeReferenceActionPerformed(evt);
            }
        });

        jLabel8.setText("Events:");

        jLabel9.setText("Events:");

        comboEventsBeforeImision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEventsBeforeImision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEventsBeforeImisionActionPerformed(evt);
            }
        });

        jLabel10.setText("Events:");

        jLabel11.setText("Events:");

        comboEventsAfterReference.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEventsAfterReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEventsAfterReferenceActionPerformed(evt);
            }
        });

        comboEventsAfterImision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEventsAfterImision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEventsAfterImisionActionPerformed(evt);
            }
        });

        labelNoiseWallEfficiencyLabel.setText("Noise wall efficiency:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        jLabel1.setText("Field");

        comboFieldType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Free field", "Reflection surface" }));

        labelNoiseWallEfficiency.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNoiseWallEfficiency.setForeground(new java.awt.Color(255, 0, 0));
        labelNoiseWallEfficiency.setText("0,0 dB");

        jLabel12.setText("Model:");

        textCalculationModelName.setText("New noise wall attenuation calculation model");

        buttonCalculationReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/History16.gif"))); // NOI18N
        buttonCalculationReport.setText("Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCalculationReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFieldType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboMeasurementBeforeReference, 0, 252, Short.MAX_VALUE)
                                    .addComponent(comboMeasurementBeforeImision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMeasurementAfterReference, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMeasurementAfterImision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboEventsBeforeReference, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboEventsBeforeImision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboEventsAfterImision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboEventsAfterReference, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHeader)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNoiseWallEfficiencyLabel)
                                .addGap(23, 23, 23)
                                .addComponent(labelNoiseWallEfficiency)))
                        .addGap(0, 293, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(89, 89, 89)
                        .addComponent(textCalculationModelName)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textCalculationModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboMeasurementBeforeReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEventsBeforeReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboMeasurementBeforeImision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(comboEventsBeforeImision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboMeasurementAfterReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(comboEventsAfterReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboMeasurementAfterImision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(comboEventsAfterImision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoiseWallEfficiencyLabel)
                    .addComponent(labelNoiseWallEfficiency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonOK)
                    .addComponent(buttonCalculationReport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        
        //ustawiamy nazwę modelu
        this.nmmNoiseWallAttenuationModel.setModelName((this.textCalculationModelName.getText()));        
        //if calculation model isn't in the project yet, than add it
        if (this.isComplete() && !this.nmmNoiseWallAttenuationModel.getProject().contains(this.nmmNoiseWallAttenuationModel)) {                    
            System.out.println("Tego modelu źródła jeszcze nie ma, dodaję ...");
            this.nmmNoiseWallAttenuationModel.getProject().addNoiseSourceModel(this.nmmNoiseWallAttenuationModel);
        }
        this.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void comboMeasurementBeforeReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeasurementBeforeReferenceActionPerformed
        this.nmmNoiseWallAttenuationModel.setMeasurementBeforeReference(this.comboMeasurementBeforeReference.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));
    }//GEN-LAST:event_comboMeasurementBeforeReferenceActionPerformed

    private void comboMeasurementBeforeImisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeasurementBeforeImisionActionPerformed
        this.nmmNoiseWallAttenuationModel.setMeasurementBeforeImision(this.comboMeasurementBeforeImision.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));
    }//GEN-LAST:event_comboMeasurementBeforeImisionActionPerformed

    private void comboMeasurementAfterReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeasurementAfterReferenceActionPerformed
        this.nmmNoiseWallAttenuationModel.setMeasurementAfterReference(this.comboMeasurementAfterReference.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));
    }//GEN-LAST:event_comboMeasurementAfterReferenceActionPerformed

    private void comboMeasurementAfterImisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeasurementAfterImisionActionPerformed
        this.nmmNoiseWallAttenuationModel.setMeasurementAfterImision(this.comboMeasurementAfterImision.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));        // TODO add your handling code here:
    }//GEN-LAST:event_comboMeasurementAfterImisionActionPerformed

    private void comboEventsBeforeReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEventsBeforeReferenceActionPerformed
        this.nmmNoiseWallAttenuationModel.setEventsBeforeReference(this.comboEventsBeforeReference.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));
    }//GEN-LAST:event_comboEventsBeforeReferenceActionPerformed

    private void comboEventsBeforeImisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEventsBeforeImisionActionPerformed
        this.nmmNoiseWallAttenuationModel.setEventsBeforeImision(this.comboEventsBeforeImision.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));
    }//GEN-LAST:event_comboEventsBeforeImisionActionPerformed

    private void comboEventsAfterReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEventsAfterReferenceActionPerformed
        this.nmmNoiseWallAttenuationModel.setEventsAfterReference(this.comboEventsAfterReference.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));
    }//GEN-LAST:event_comboEventsAfterReferenceActionPerformed

    private void comboEventsAfterImisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEventsAfterImisionActionPerformed
        this.nmmNoiseWallAttenuationModel.setEventsAfterImision(this.comboEventsAfterImision.getSelectedItem());
        this.nmmNoiseWallAttenuationModel.recalculateModel();
        this.labelNoiseWallEfficiency.setText(String.valueOf(this.nmmNoiseWallAttenuationModel.getNoiseModelResult(NoiseLevelIndicators.DILp)));    
    }//GEN-LAST:event_comboEventsAfterImisionActionPerformed
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculationReport;
    private javax.swing.JButton buttonOK;
    private javax.swing.JComboBox comboEventsAfterImision;
    private javax.swing.JComboBox comboEventsAfterReference;
    private javax.swing.JComboBox comboEventsBeforeImision;
    private javax.swing.JComboBox comboEventsBeforeReference;
    private javax.swing.JComboBox comboFieldType;
    private javax.swing.JComboBox comboMeasurementAfterImision;
    private javax.swing.JComboBox comboMeasurementAfterReference;
    private javax.swing.JComboBox comboMeasurementBeforeImision;
    private javax.swing.JComboBox comboMeasurementBeforeReference;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelNoiseWallEfficiency;
    private javax.swing.JLabel labelNoiseWallEfficiencyLabel;
    private javax.swing.JTextField textCalculationModelName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispatchNMMProjectModelsChanged(NMMProjectModelsChanged _mEvent) {
        System.out.println("Zmieniło sie cos w zawartości modeli projektu, ale akurat nie jestem zainteresowany...");
    }

    @Override
    public boolean isComplete() {
        
        boolean completeForm=false;        
        if (this.comboEventsAfterImision.getSelectedIndex()!=-1 &&
                this.comboEventsAfterReference.getSelectedIndex()!=-1 &&
                this.comboEventsBeforeImision.getSelectedIndex()!=-1 &&
                this.comboEventsBeforeReference.getSelectedIndex()!=-1 &&
                this.comboFieldType.getSelectedIndex()!=-1 &&
                this.comboMeasurementAfterImision.getSelectedIndex()!=-1 &&
                this.comboMeasurementAfterReference.getSelectedIndex()!=-1 &&
                this.comboMeasurementBeforeReference.getSelectedIndex()!=-1 &&
                this.comboMeasurementBeforeImision.getSelectedIndex()!=-1)
        {
            completeForm=true;
        }       
        return completeForm;
    }

    @Override
    public void dispatchNMMNoiseSourceModelChanged(NMMNoiseSourceModel _mEvent) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
