/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NMMNoiseMeasurementSetProperties.java
 *
 * Created on 2011-02-08, 23:42:49
 */

package biz.ekoplan.nmm2010.devices;

import javax.swing.JOptionPane;
import nmm2010.NMMProject;

/**
 *
 * @author Jarek
 */
public class NMMNoiseMeasurementSetProperties extends javax.swing.JDialog {

    boolean dataChanged=false;
    NMMProject nmmProj;

    /** Creates new form NMMNoiseMeasurementSetProperties */
    public NMMNoiseMeasurementSetProperties(java.awt.Frame parent,
            boolean modal, NMMProject _nmmProject) {

        super(parent, modal);
        this.nmmProj=_nmmProject;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textMeasurementSetDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textMeasurementSetCalibration = new javax.swing.JTextField();
        comboMeasurementSet = new javax.swing.JComboBox();
        buttonCancel = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        textMeasurementSet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textUncertaintyB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Measurement sets");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Measurement set ID");

        jLabel2.setText("Set description");

        jLabel3.setText("Set calibration");

        comboMeasurementSet.setMaximumRowCount(17);
        comboMeasurementSet.setModel(this.nmmProj.getMeasuringSets());
        comboMeasurementSet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMeasurementSetItemStateChanged(evt);
            }
        });
        comboMeasurementSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeasurementSetActionPerformed(evt);
            }
        });
        comboMeasurementSet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comboMeasurementSetKeyTyped(evt);
            }
        });

        buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/Stop16.gif"))); // NOI18N
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/Add16.gif"))); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toolbarButtonGraphics/general/Delete16.gif"))); // NOI18N
        buttonRemove.setText("Delete");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        jLabel4.setText("Uncertainty B");

        textUncertaintyB.setText("0.9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMeasurementSetDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addComponent(textMeasurementSetCalibration, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textMeasurementSet, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMeasurementSet, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textUncertaintyB, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboMeasurementSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMeasurementSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textMeasurementSetDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textMeasurementSetCalibration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCancel)
                            .addComponent(buttonRemove)
                            .addComponent(buttonAdd)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textUncertaintyB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void comboMeasurementSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeasurementSetActionPerformed

        int csi= this.comboMeasurementSet.getSelectedIndex();
        System.out.println("Zdarzenie ActionPerformed.");
        System.out.println("aktualny indeks combo: "+csi);
        System.out.println("aktualny obiekt combo: "+this.comboMeasurementSet.getSelectedItem().toString());

        NMMNoiseMeasurementSet nms=(NMMNoiseMeasurementSet)this.comboMeasurementSet.getModel().getSelectedItem();
        this.textMeasurementSet.setText(nms.getLaboratoryID());
        this.textMeasurementSetCalibration.setText(
             nms.getCalibrationInfo());
        this.textMeasurementSetDescription.setText(
                nms.getMeasurementSetDescription());
        this.textUncertaintyB.setText(String.valueOf(nms.getUncertaintyB()));
    }//GEN-LAST:event_comboMeasurementSetActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        NMMNoiseMeasurementSet nms = new NMMNoiseMeasurementSet(
                this.textMeasurementSet.getText(),
                this.textMeasurementSetDescription.getText(),
                this.textMeasurementSetCalibration.getText(),
                Double.valueOf(this.textUncertaintyB.getText()));
        System.out.println(Double.valueOf(this.textUncertaintyB.getText()));
        this.nmmProj.addMeasurementSet(nms);
        this.nmmProj.setSaved(false);
        this.dispose();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        int selIndex=this.comboMeasurementSet.getSelectedIndex();
        //System.out.println("Wybrany index na liście dostepnych zestawów pomiarowych: "+selIndex);
        if ((selIndex>-1) & (this.comboMeasurementSet.getModel().getSize()>0)) {
            if (JOptionPane.showConfirmDialog(this,
                    "Delete selected measuring set?")==JOptionPane.YES_OPTION) {
                this.nmmProj.getMeasuringSets().measurementSets.remove(selIndex);
            } else {

            }    
        } else {
            JOptionPane.showMessageDialog(this, "Select measuring set first!",
                    "NMM Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void comboMeasurementSetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMeasurementSetItemStateChanged
        System.out.println("Wystapiło zdarzenie ItemStateChanged!");
    }//GEN-LAST:event_comboMeasurementSetItemStateChanged

    private void comboMeasurementSetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboMeasurementSetKeyTyped
        System.out.println("Wystapiło zdarzenie klawiatury!");        
    }//GEN-LAST:event_comboMeasurementSetKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("Okno otwarte");
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JComboBox comboMeasurementSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textMeasurementSet;
    private javax.swing.JTextField textMeasurementSetCalibration;
    private javax.swing.JTextField textMeasurementSetDescription;
    private javax.swing.JTextField textUncertaintyB;
    // End of variables declaration//GEN-END:variables

}
