/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.ekoplan.nmm2010.measurement;

import biz.ekoplan.nmm2010.enums.RecordValueType;
import biz.ekoplan.nmm2010.toolbox.TimeConverter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import nmm2010.NMMProject;

/**
 *
 * @author User
 */
public class NMMCreateMeasurement extends javax.swing.JDialog {

    Locale loc;
    NMMProject nmmProj;
    
    
    /**
     * Creates new form NMMCreateMeasurement
     */
    public NMMCreateMeasurement(java.awt.Frame parent, boolean modal, Locale _locale, NMMProject _nmmProj) {
        super(parent, modal);        
        loc = _locale;
        nmmProj = _nmmProj;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textMID = new javax.swing.JTextField();
        buttonCancel = new javax.swing.JButton();
        buttonCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textDate = new javax.swing.JTextField();
        textTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textMDuration = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textMValue = new javax.swing.JTextField();
        comboFillOutForm1 = new javax.swing.JComboBox();
        chkboxRandom = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        textRandomPlusMinus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("biz/ekoplan/nmm2010/languages/translations"); // NOI18N
        setTitle(bundle.getString("CREATE MEASUREMENT")); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("biz/ekoplan/nmm2010/languages/translations_pl_PL"); // NOI18N
        jLabel1.setText(bundle1.getString("MEASUREMENT ID")); // NOI18N

        textMID.setText(bundle.getString("NEW MEASUREMENT")); // NOI18N

        buttonCancel.setText(bundle.getString("CANCEL")); // NOI18N
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonCreate.setText(bundle.getString("CREATE")); // NOI18N
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("START DATE AND TIME")); // NOI18N

        textDate.setText(bundle.getString("YYYY-MM-DD")); // NOI18N

        textTime.setText(bundle.getString("GG:MM:SS")); // NOI18N

        jLabel3.setText(bundle.getString("MEASUREMENT DURATION [SEC.]")); // NOI18N

        textMDuration.setText("3600");

        jLabel4.setText(bundle.getString("VALUE [DB]")); // NOI18N

        textMValue.setText("40");

        comboFillOutForm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Now", "Begining of project", "End of last measurement" }));
        comboFillOutForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFillOutForm1ActionPerformed(evt);
            }
        });

        chkboxRandom.setText(bundle.getString("RANDOM")); // NOI18N
        chkboxRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxRandomActionPerformed(evt);
            }
        });

        jLabel5.setText("+/-");

        textRandomPlusMinus.setText("0");
        textRandomPlusMinus.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTime, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboFillOutForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMDuration))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMValue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkboxRandom)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textRandomPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textMID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFillOutForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textMDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textMValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkboxRandom)
                    .addComponent(jLabel5)
                    .addComponent(textRandomPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonCreate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        
        //tworzenie nowego pomiaru
        NMMMeasurement m = new NMMMeasurement(this.textDate.getText(), this.textTime.getText(),1000,loc);
        //zapełnianie pomiaru danymi
        int l;
        double val;
        double rnd;
        double pm;
        l=Integer.parseInt(this.textMDuration.getText());        
        val = Double.parseDouble(this.textMValue.getText());
        pm = Double.parseDouble(this.textRandomPlusMinus.getText());       
        for (int i=0; i<=l;i++) {
            if (this.chkboxRandom.isSelected()) {
                val = Double.parseDouble(this.textMValue.getText());
                rnd=Math.random()*2*pm;
                val=val+rnd-pm;
            }            
            m.addRecord(RecordValueType.LAeq, val);
        }        
        this.nmmProj.addMeasurement(m);          
        this.dispose();
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void comboFillOutForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFillOutForm1ActionPerformed
                
        switch (this.comboFillOutForm1.getSelectedIndex()) {
            case 0: {                
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                DateFormat timeFormat = new SimpleDateFormat("kk:mm:ss");                
                Calendar cal = Calendar.getInstance();
                this.textDate.setText(dateFormat.format(cal.getTime()));
                this.textTime.setText(timeFormat.format(cal.getTime()));
            }
            case 1: {
                //początek projektu
                this.textDate.setText(TimeConverter.LongToDateString(this.nmmProj.getProjectBeginTime(), DateFormat.SHORT, loc));
                this.textTime.setText(TimeConverter.LongToTimeString(this.nmmProj.getProjectBeginTime(), DateFormat.SHORT, loc));
            }
            
            case 2: {
                //koniec ostatniego zapisu w projekcie
                this.textDate.setText(TimeConverter.LongToDateString(this.nmmProj.getProjectEndTime(), DateFormat.SHORT, loc));
                this.textTime.setText(TimeConverter.LongToTimeString(this.nmmProj.getProjectEndTime(), DateFormat.SHORT, loc));                
            }
    }
    }//GEN-LAST:event_comboFillOutForm1ActionPerformed

    private void chkboxRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxRandomActionPerformed
        
        if (this.chkboxRandom.isSelected()) {
            this.textRandomPlusMinus.setEnabled(true);
        } else {
            this.textRandomPlusMinus.setEnabled(false);
        }                        
    }//GEN-LAST:event_chkboxRandomActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JCheckBox chkboxRandom;
    private javax.swing.JComboBox comboFillOutForm1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textMDuration;
    private javax.swing.JTextField textMID;
    private javax.swing.JTextField textMValue;
    private javax.swing.JTextField textRandomPlusMinus;
    private javax.swing.JTextField textTime;
    // End of variables declaration//GEN-END:variables
}
